### ISSUE TITLE
En tant que développeur, j'aimerais que l'application fonctionne sur mobile peut importe depuis quelle machine elle est déployée

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_mobile#107]
Actuellement, lorsque l'app est déployée depuis le Mac de @Kagelmacher , elle ne parvient pas à accéder au backend. Alors que lorsqu'elle est déployée depuis l'Asus de @seza443 , il n'y a pas de souci.

- [x] Vérifier si ce n'est pas dû à une version différente du SDK Android

**Comment by Kagelmacher** [comment]
http://stackoverflow.com/questions/30161952/ionic-angular-how-to-avoid-the-404-not-found-from-cache-after-post-reque

**Comment by Kagelmacher** [comment]
http://stackoverflow.com/questions/30161952/ionic-angular-how-to-avoid-the-404-not-found-from-cache-after-post-reque
