### ISSUE TITLE
En tant qu'utilisateur, lorsque j'ajoute un symptôme et qu'il est déjà existant, j'aimerais qu'il n'y ait pas de doublon

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_mobile#110]

**Comment by seza443** [comment]
Si on fait d'abord la #95, alors on peut faire la vérification côté backend. En effet, chaque utilisateur aura une liste de symptomes "favoris" à afficher sur son écran d'accueil qui sera enregistrée côté backend afin de synchroniser cette liste entre ses différents appareils.

**Comment by Kagelmacher** [comment]
@seza443 donc on peut la fermer avec la #95 mais il est peut être préférable d'afficher un message d'erreur ?

**Comment by seza443** [comment]
Je dirai qu'on peut la fermer directement et faire une nouvelle carte pour le message d'erreur @kagelmacher

-----Message d'origine-----
De : "Alexandre Hauet" <notifications@github.com>
Envoyé : ‎11/‎03/‎2017 09:42
À : "GeoHealth/HAppi_mobile" <HAppi_mobile@noreply.github.com>
Cc : "Tanguy Vaessen" <tanguy.vaessen@gmail.com>; "Mention" <mention@noreply.github.com>
Objet : Re: [GeoHealth/HAppi_mobile] En tant qu'utilisateur, lorsque j'ajoute un symptôme et qu'il est déjà existant, j'aimerais qu'il n'y ait pas de doublon (#110)

@seza443 donc on peut la fermer avec la #95 mais il est peut être préférable d'afficher un message d'erreur ?

**Comment by Kagelmacher** [comment]
@seza443  Ok :-)
