### ISSUE TITLE
Afficher le nom, prénom et mail de l'utilisateur loggué dans le menu

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_mobile#121]

**Comment by Kagelmacher** [comment]
Suite à notre rendez-vous avec un médecin, l'information sur le sexe du patient est une information pertinente.

**Comment by Kagelmacher** [comment]
https://github.com/GeoHealth/HAppi_mobile/commit/fd82c46d9e6dcbe02ddf442a9985055ed00ae052
