### ISSUE TITLE
Créer post/get/delete shared_occurrence

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_mobile#129]
Attention il faudra peut être faire plus de "process".

**Comment by seza443** [comment]
- [ ] POST
- [ ] GET
- [ ] DELETE

**Comment by seza443** [comment]
GET params
- Email du médecin
- Une date de début
- Une date de fin
- Une date d'expiration (par défaut 2 semaines?) après laquelle le rapport n'est plus consultable

**Comment by seza443** [comment]
Issue moved to [GeoHealth/HAppi_backend #45](https://github.com/GeoHealth/HAppi_backend/issues/45) via [**ZenHub**](https://www.zenhub.com/)
