### ISSUE TITLE
Respect vie privée - afficher un message avertissant l'utilisateur 

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_mobile#133]

**Comment by seza443** [comment]
@Kagelmacher Est-ce qu'on ne ferait pas aussi un message lors de l'envoi d'un rapport au médecin, pour bien préciser à l'utilisateur que son médecin aura accès à sa position, etc?

**Comment by Kagelmacher** [comment]
@seza443 oui c'est une très bonne idée
