### ISSUE TITLE
Elastic, Kibana, (logstash) => affichage des données simulée

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_mobile#135]
https://www.elastic.co/products/kibana 

logstash c'est pour les logs: https://www.elastic.co/products/logstash

**Comment by seza443** [comment]
Flyn elastic search : https://github.com/jobready/flynn-elasticsearch

**Comment by seza443** [comment]
https://flynn.io/docs/languages/java

**Comment by seza443** [comment]
Not deployed on Flynn

**Comment by Kagelmacher** [comment]
https://geohealth-kibana.herokuapp.com/app/kibana#/dashboard/Main?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fy,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:7,id:Count-Symptom,panelIndex:1,row:1,size_x:6,size_y:4,type:visualization),(col:1,id:Nb-occ,panelIndex:2,row:1,size_x:3,size_y:2,type:visualization),(col:1,id:symptom-user,panelIndex:3,row:3,size_x:6,size_y:4,type:visualization),(col:7,id:Symptom-maps,panelIndex:4,row:5,size_x:6,size_y:3,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:Main,uiState:(P-1:(spy:(mode:(fill:!f,name:!n)),vis:(legendOpen:!f))))
