### ISSUE TITLE
En tant qu'utilisateur, j'aimerais ajouter une occurrence d'un symptôme en fournissant des détails afin de d'obtenir un meilleur diagnostic chez mon médecin

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_mobile#29]
Créer un écran permettant d'encoder un symptome de manière détaillée, avec 

- [x] saisie manuelle de la date et l'heure
- [x] saisie d'un commentaire personnel
- [x] Sauver la position
- [x] Sauver le commentaire (en tant que Factor?)
- [x] Désactiver le bouton onclick
- [x] Rediriger vers la HomePage quand la sauvegarde est terminée

**Comment by seza443** [comment]
Je vais fermer cette issue pour le moment. Il faudra néanmoins améliorer cet écran par la suite

**Comment by seza443** [comment]
Un symptôme a une liste de facteurs qui lui sont associés.
L'écran d'encodage détaillé affiche une liste de ces facteurs.
Chaque élément de cette liste est affiché d'une manière personnalisée selon le type du facteur courant. Par exemple, un facteur de type "comment" sera présenté sous la forme d'un text area tandis qu'un facteur de type "pain-severity" sera présenté sous la forme d'un curseur pouvant aller de 1 à 10.
