### ISSUE TITLE
En tant qu'utilisateur je voudrais pouvoir accéder aux statistiques de mes symptômes afin de pouvoir surveiller l'évolution de ceux-ci

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_mobile#35]
- [x] Afficher l'apparition des symptoms sur une carte

**Comment by Kagelmacher** [comment]
Cette carte est vraiment vague, je propose de la splitter

**Comment by seza443** [comment]
Do it! 😄 
![laboeuf](https://media.giphy.com/media/10FUfTApAeoZK8/giphy.gif)
