### ISSUE TITLE
En tant qu'utilisateur je voudrais avoir l'application dans ma langue préférée afin de faciliter l'utilisation de l'application

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_mobile#48]
voir
- https://www.gnu.org/software/gettext/
- https://fr.wikipedia.org/wiki/GNU_gettext

**Comment by seza443** [comment]
http://mcgivery.com/internationalization-of-an-ionic-app-multilanguage-support/

**Comment by seza443** [comment]
Cette librairie est une implémentation de GNU gettext en javascript
https://sourceforge.net/projects/jsgettext.berlios/

**Comment by seza443** [comment]
Il y a également cette librairie : http://www.zomeoff.com/jsin/

**Comment by seza443** [comment]
On utilise la librairie javascript [Gettext](https://sourceforge.net/projects/jsgettext.berlios/).
La classe TranslationProvider crée une instance de cette librairie avec le fichier JSON contenant les traductions de la langue de l'utilisateur.

## Comment sont générés les fichiers JSON avec les traductions ?
- Nous utilisons POEdit pour
  * analyser notre code source et extraire les traductions
  * générer des fichiers .PO 
- Nous utilisons [po2json](https://www.npmjs.com/package/po2json) pour
  * convertir les fichiers .PO en .JSON

**Comment by seza443** [comment]
Ca fonctionne dans un browser quand on lance `ionic run browser` mais pas avec `ionic serve`
https://forum.ionicframework.com/t/globalization-in-browser-throws-cordova-not-available/74399

**Comment by seza443** [comment]
closed by 2cab08e
