### ISSUE TITLE
En tant que développeur, je voudrais que mon application soit déployé dans  un store afin que des utilisateurs puissent la tester

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_mobile#52]
- [Ionic view](http://view.ionic.io/)

**Comment by seza443** [comment]
L'application est déployée sur Ionic View.
Pour la tester:

- Installer [Ionic View](http://view.ionic.io/)
- Lancer l'app et se logger
- Prévisualiser l'app avec l'identifiant **317959d7**

**Comment by seza443** [comment]
ionic package build android
