### ISSUE TITLE
En tant qu'utilisateur, je voudrais accéder à la liste de mes symptômes sur tous mes appareils.

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_mobile#95]
Liés la liste de symptômes à l'utilisateur et la sauver côté backend

- [x] Créer un modèle "SymptomsUser" côté backend
- [x] Pouvoir ajouter/supprimer un symptome à la liste des SymptomsUser d'un utilisateur
    - Un utilisateur ne peut modifier que sa propre liste
    - Modifier le swagger.yml en conséquence
- [x] Lors de l'ajout d'un symptome côté mobile, l'ajouter aussi côté backend
- [x] Lors de la suppression d'un symptome côté mobile, le supprimer aussi côté backend
- [x] Lors du login d'un utilisateur, récupérer la liste des SymptomsUser et la sauver dans le device

**Comment by Kagelmacher** [comment]
close by the commit 4e1fcc18858172583b3165c663488d30c17f9267 on the backend

**Comment by Kagelmacher** [comment]
@seza443 Tu sais regarder si au niveau test tout est ok ?

**Comment by seza443** [comment]
@Kagelmacher j'ai ajouté quelques commentaires dans les commits :)
